on: push

name: Integration

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        env:
          DOCKER_USERNAME: jafarsw
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: docker build
        run: |
          docker build -t jafarsw/my-test-image:latest .

      - name: docker push
        run: |
          docker push jafarsw/my-test-image:latest
