on: push

name: Integration

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jafarsw
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: docker build
        run: |
          docker build -t jafarsw/my-test-image:latest .

      - name: docker push
        run: |
          docker push docker.io/jafarsw/my-test-image:latest
